---
- name: Create /root/.aws/ directory if it does not exist
  file: 
    path: /root/.aws/
    state: directory
    mode: 0400
    owner: root
    group: root
  become: true

- name: Create file for aws credentials
  template: 
    src: aws-config.j2 
    dest: "/root/.aws/config"
    mode: 0400
    owner: root
    group: root
  become: true

- name: Add cron job for certbot renewal (if configured).
  cron:
    name: Certbot automatic renewal.
    job: "{{ certbot_script }} renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
  become: true
