---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first }}/cert.pem
  register: letsencrypt_cert

- name: Create deploy scripts for the certificate
  template: 
    src: domain-deployer.sh.j2 
    dest: "/etc/letsencrypt/renewal-hooks/{{ cert_item.domains | first }}-deployer.sh"
    mode: 0500
    owner: root
    group: root
  become: true
  when: certbot_deploy_hook and (certbot_combine_cert is defined or cert_item.certbot_combine_cert is defined)

- name: Create webroot directory if it doesn't exist yet
  file:
    path: "{{ cert_item.webroot | default(certbot_webroot) }}"
    state: directory

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists
